Aqui algunos criterios segun la api de COINGENKO para elegir las 10 cryptos mas rentables, mas seguras, del mercado, basandonos para empezar por las 13 criptomonedas con mejor <strong>capitalizacion de mercado</strong>, como kpi principal de criptomonedas mas establecidas en el mercado, luego compararemos y analizaremos con los otros 2 KPIs, Volatilización en 30 dias, y Volumen de operaciones en 24hs, y cotejaremos luego con otra api como Binance api, y nos quedaremos con 10 criptomonedas estables, seguras y rentables, pero por ahora nos basamos en esta primera Información para un primer EDA con datos de hoy 25/8/23:

In [1]:
import pandas as pd
import requests

url = "https://api.coingecko.com/api/v3/coins/markets"
parametros = {
    "vs_currency": "usd",
    "order": "market_cap_desc",
    "per_page": 13,
    "page": 1
}
respuesta = requests.get(url, params=parametros)
top_13_monedas = respuesta.json()

# Crear una lista para almacenar los datos de todas las criptomonedas
filas_datos = []

for moneda in top_13_monedas:
    id_moneda = moneda["id"]
    url = f"https://api.coingecko.com/api/v3/coins/{id_moneda}?\
        localization=false&tickers=false&market_data=true&community_data=false&developer_data=false&sparkline=false"

    respuesta = requests.get(url)
    datos = respuesta.json()

    datos_mercado = datos.get("market_data")

    if datos_mercado:
        datos_filtrados = {
            "id": id_moneda,
            "simbolo": datos.get("symbol"),
            "nombre": datos.get("name"),
            "fecha_genesis": datos.get("genesis_date"),
            "porcentaje_votos_positivos": datos.get("sentiment_votes_up_percentage"),
            "porcentaje_votos_negativos": datos.get("sentiment_votes_down_percentage"),
            "usuarios_lista_seguimiento": datos.get("watchlist_portfolio_users"),
            "ranking_cap_mercado": datos.get("market_cap_rank"),
            "ranking_coingecko": datos.get("coingecko_rank"),
            "puntuacion_coingecko": datos.get("coingecko_score"),
            "puntuacion_desarrollador": datos.get("developer_score"),
            "puntuacion_comunidad": datos.get("community_score"),
            "puntuacion_liquidez": datos.get("liquidity_score"),
            "puntuacion_interes_publico": datos.get("public_interest_score"),
            "precio_actual_usd": datos_mercado["current_price"]["usd"],
            "precio_maximo_historico_usd": datos_mercado["ath"]["usd"],
            "precio_minimo_historico_usd": datos_mercado["atl"]["usd"],
            "capitalizacion_mercado_usd": datos_mercado["market_cap"]["usd"],
            "valoracion_total_diluida_usd": datos_mercado["fully_diluted_valuation"]["usd"],
            "volumen_total_usd": datos_mercado["total_volume"]["usd"],
            "alto_24h_usd": datos_mercado["high_24h"]["usd"],
            "bajo_24h_usd": datos_mercado["low_24h"]["usd"],
            "cambio_precio_24h_usd": datos_mercado["price_change_24h_in_currency"]["usd"],
            "oferta_total": datos_mercado["total_supply"],
            "oferta_maxima": datos_mercado["max_supply"],
            "oferta_circulante": datos_mercado["circulating_supply"]
        }
    else:
        datos_filtrados = {
            "id": id_moneda,
            "simbolo": datos.get("symbol"),
            "nombre": datos.get("name"),
            "fecha_genesis": datos.get("genesis_date"),
            "porcentaje_votos_positivos": datos.get("sentiment_votes_up_percentage"),
            "porcentaje_votos_negativos": datos.get("sentiment_votes_down_percentage"),
            "usuarios_lista_seguimiento": datos.get("watchlist_portfolio_users"),
            "ranking_cap_mercado": datos.get("market_cap_rank"),
            "ranking_coingecko": datos.get("coingecko_rank"),
            "puntuacion_coingecko": datos.get("coingecko_score"),
            "puntuacion_desarrollador": datos.get("developer_score"),
            "puntuacion_comunidad": datos.get("community_score"),
            "puntuacion_liquidez": datos.get("liquidity_score"),
            "puntuacion_interes_publico": datos.get("public_interest_score"),
        }

    filas_datos.append(datos_filtrados)

# Crear el DataFrame utilizando la lista de datos filtrados
df = pd.DataFrame(filas_datos)

# Rellenar valores nulos con "Sin Dato"
df = df.fillna("Sin Dato")

"""aqui haremos parte del ETL:

Para columnas numéricas:

count: número de valores no nulos.
mean: media aritmética.
std: desviación estándar.
min: valor mínimo.
25%: percentil 25.
50%: mediana o percentil 50.
75%: percentil 75.
max: valor máximo.

Para columnas no numéricas (por ejemplo, tipo object o categorial):

count: número de valores no nulos.
unique: número de valores únicos.
top: valor más común.
freq: frecuencia del valor más común."""

print("------------------------------")
print(df.info())
print("------------------------------")
print(df.describe(include="all"))
print("------------------------------")

# Mostrar el DataFrame resultante
df

------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            13 non-null     object
 1   simbolo                       13 non-null     object
 2   nombre                        13 non-null     object
 3   fecha_genesis                 13 non-null     object
 4   porcentaje_votos_positivos    13 non-null     float64
 5   porcentaje_votos_negativos    13 non-null     float64
 6   usuarios_lista_seguimiento    13 non-null     int64
 7   ranking_cap_mercado           13 non-null     int64
 8   ranking_coingecko             13 non-null     int64
 9   puntuacion_coingecko          13 non-null     float64
 10  puntuacion_desarrollador      13 non-null     float64
 11  puntuacion_comunidad          13 non-null     float64
 12  puntuacion_liquidez           13 non-null     float64
 13  puntuacion_interes_publico    13 non-null     float64
 14  precio_actual_usd             13 non-null     float64
 15  precio_maximo_historico_usd   13 non-null     float64
 16  precio_minimo_historico_usd   13 non-null     float64
 17  capitalizacion_mercado_usd    13 non-null     int64
 18  valoracion_total_diluida_usd  13 non-null     int64
 19  volumen_total_usd             13 non-null     int64
 20  alto_24h_usd                  13 non-null     float64
 21  bajo_24h_usd                  13 non-null     float64
 22  cambio_precio_24h_usd         13 non-null     float64
 23  oferta_total                  13 non-null     float64
 24  oferta_maxima                 13 non-null     object
 25  oferta_circulante             13 non-null     float64
dtypes: float64(15), int64(6), object(5)
memory usage: 2.8+ KB
None
------------------------------
             id simbolo   nombre fecha_genesis  porcentaje_votos_positivos  \
count        13      13       13            13                   13.000000
unique       13      13       13             6                         NaN
top     bitcoin     btc  Bitcoin      Sin Dato                         NaN
freq          1       1        1             8                         NaN
mean        NaN     NaN      NaN           NaN                   62.818462
std         NaN     NaN      NaN           NaN                    8.998977
min         NaN     NaN      NaN           NaN                   47.830000
25%         NaN     NaN      NaN           NaN                   56.250000
50%         NaN     NaN      NaN           NaN                   62.130000
75%         NaN     NaN      NaN           NaN                   70.440000
max         NaN     NaN      NaN           NaN                   74.710000

        porcentaje_votos_negativos  usuarios_lista_seguimiento  \
count                    13.000000                1.300000e+01
unique                         NaN                         NaN
top                            NaN                         NaN
freq                           NaN                         NaN
mean                     37.181538                5.554066e+05
std                       8.998977                3.793245e+05
min                      25.290000                1.311900e+04
25%                      29.560000                2.843790e+05
50%                      37.870000                5.457570e+05
75%                      43.750000                6.429940e+05
max                      52.170000                1.332601e+06

        ranking_cap_mercado  ranking_coingecko  puntuacion_coingecko  ...  \
count              13.00000          13.000000             13.000000  ...
unique                  NaN                NaN                   NaN  ...
top                     NaN                NaN                   NaN  ...
freq                    NaN                NaN                   NaN  ...
mean                7.00000          42.076923             60.682154  ...
std                 3.89444          75.841349             13.433677  ...
min                 1.00000           1.000000             34.763000  ...
25%                 4.00000           4.000000             53.898000  ...
50%                 7.00000           7.000000             62.536000  ...
75%                10.00000          28.000000             65.857000  ...
max                13.00000         253.000000             83.151000  ...

        precio_minimo_historico_usd  capitalizacion_mercado_usd  \
count                     13.000000                1.300000e+01
unique                          NaN                         NaN
top                             NaN                         NaN
freq                            NaN                         NaN
mean                      42.758518                7.137019e+10
std                      133.551380                1.402957e+11
min                        0.000087                5.049276e+09
25%                        0.003144                8.269329e+09
50%                        0.432979                1.373673e+10
75%                        0.877647                3.336745e+10
max                      482.900000                5.035801e+11

        valoracion_total_diluida_usd  volumen_total_usd  alto_24h_usd  \
count                   1.300000e+01       1.300000e+01     13.000000
unique                           NaN                NaN           NaN
top                              NaN                NaN           NaN
freq                             NaN                NaN           NaN
mean                    7.755790e+10       2.845153e+09   2290.331382
std                     1.495942e+11       5.018459e+09   7210.105123
min                     5.417987e+09       7.677610e+06      0.063030
25%                     8.771538e+09       2.183896e+08      0.521617
50%                     1.373673e+10       2.771872e+08      1.003000
75%                     5.197371e+10       4.054821e+09    219.050000
max                     5.432179e+11       1.745463e+10  26200.000000

        bajo_24h_usd  cambio_precio_24h_usd  oferta_total  oferta_maxima  \
count      13.000000              13.000000  1.300000e+01             13
unique           NaN                    NaN           NaN              7
top              NaN                    NaN           NaN       Sin Dato
freq             NaN                    NaN           NaN              7
mean     2256.411401             -12.772061  3.815516e+10            NaN
std      7105.636601              41.060033  4.875707e+10            NaN
min         0.061847            -149.082676  8.377739e+06            NaN
25%         0.508245              -0.712291  1.538562e+08            NaN
50%         0.997937              -0.001609  1.000000e+10            NaN
75%       214.120000               0.000121  8.284913e+10            NaN
max     25820.000000               0.025993  1.407371e+11            NaN

        oferta_circulante
count        1.300000e+01
unique                NaN
top                   NaN
freq                  NaN
mean         3.369821e+10
std          4.535242e+10
min          8.377739e+06
25%          1.538562e+08
50%          9.319469e+09
75%          5.291419e+10
max          1.407372e+11

[11 rows x 26 columns]
------------------------------

,id,simbolo,nombre,fecha_genesis,porcentaje_votos_positivos,porcentaje_votos_negativos,usuarios_lista_seguimiento,ranking_cap_mercado,ranking_coingecko,puntuacion_coingecko,...,precio_minimo_historico_usd,capitalizacion_mercado_usd,valoracion_total_diluida_usd,volumen_total_usd,alto_24h_usd,bajo_24h_usd,cambio_precio_24h_usd,oferta_total,oferta_maxima,oferta_circulante
0,bitcoin,btc,Bitcoin,2009-01-03,62.13,37.87,1332601,1,1,83.151,...,67.810000,503580110214,543217892035,5675162795,26200.000000,25820.000000,-149.082676,2.100000e+07,21000000.0,1.946766e+07
1,ethereum,eth,Ethereum,2015-07-30,63.64,36.36,1194515,2,2,78.783,...,0.432979,197248313062,197248313062,7276891213,1664.660000,1636.870000,-7.599117,1.202164e+08,Sin Dato,1.202164e+08
2,tether,usdt,Tether,Sin Dato,56.25,43.75,284379,3,150,41.416,...,0.572521,82774968781,82774968781,17454631744,1.002000,0.997937,-0.000041,8.284913e+10,Sin Dato,8.284913e+10
3,binancecoin,bnb,BNB,2017-07-08,61.82,38.18,642994,4,5,65.446,...,0.039818,33367452194,43374869570,392292742,219.050000,214.120000,-0.443358,1.538562e+08,200000000.0,1.538562e+08
4,ripple,xrp,XRP,Sin Dato,70.44,29.56,569536,5,3,66.223,...,0.002686,27501467937,51973707036,865092243,0.521617,0.508245,0.004504,9.998849e+10,100000000000.0,5.291419e+10
5,usd-coin,usdc,USD Coin,Sin Dato,69.23,30.77,109856,6,28,53.898,...,0.877647,25875816011,25875831765,4054821069,1.003000,0.997858,0.001499,2.585702e+10,Sin Dato,2.585701e+10
6,staked-ether,steth,Lido Staked Ether,Sin Dato,50.00,50.00,13119,7,253,34.763,...,482.900000,13736730865,13736730865,7677610,1661.590000,1634.300000,-8.225069,8.377739e+06,8377738.530266,8.377739e+06
7,cardano,ada,Cardano,Sin Dato,74.71,25.29,724997,8,7,62.536,...,0.019253,9139380529,11735536577,218389639,0.269557,0.259564,-0.004296,4.500000e+10,45000000000.0,3.504502e+10
8,dogecoin,doge,Dogecoin,2013-12-08,54.72,45.28,506468,9,6,65.012,...,0.000087,8771545732,8771538253,231847821,0.063030,0.061847,-0.000452,1.407371e+11,Sin Dato,1.407372e+11
9,solana,sol,Solana,Sin Dato,59.46,40.54,554152,10,4,65.857,...,0.500801,8269328828,11268252936,277187182,21.040000,20.260000,-0.712291,5.558186e+08,Sin Dato,4.078935e+08
10,tron,trx,TRON,2017-08-28,47.83,52.17,227880,11,13,60.859,...,0.001804,6873823305,6873835824,189472135,0.077328,0.076247,0.000121,8.937720e+10,Sin Dato,8.937704e+10
11,polkadot,dot,Polkadot,Sin Dato,71.74,28.26,514032,12,9,62.064,...,2.700000,5624220972,5983288198,97803391,4.480000,4.360000,0.025993,1.348852e+09,Sin Dato,1.267905e+09
12,matic-network,matic,Polygon,Sin Dato,74.67,25.33,545757,13,66,48.860,...,0.003144,5049275954,5417986708,245724791,0.551440,0.536517,-0.001609,1.000000e+10,10000000000.0,9.319469e+09

In [2]:

# Guardar todos los datos en un único archivo CSV
df.to_csv("KPIs_coingecko_kpis.csv", index=False)

In [3]:
df['ranking_coingecko'] = pd.to_numeric(df['ranking_coingecko'], errors='coerce')
# 1. Ordenar por 'ranking_coingecko'
df_ordenado_ranking_coingecko = df.sort_values(by='ranking_coingecko', ascending=True).head(10)[['nombre', 'ranking_coingecko']]

df['puntuacion_coingecko'] = pd.to_numeric(df['puntuacion_coingecko'], errors='coerce')
# 2. Ordenar por 'puntuacion_coingecko'
df_ordenado_puntuacion_coingecko = df.sort_values(by='puntuacion_coingecko', ascending=False).head(10)[['nombre', 'puntuacion_coingecko']]

df['capitalizacion_mercado_usd'] = pd.to_numeric(df['capitalizacion_mercado_usd'], errors='coerce')
#3. Ordenar por 'capitalizacion_mercado_usd' 
df_ordenado_capitalizacion_mercado_usd = df.sort_values(by='capitalizacion_mercado_usd', ascending=False).head(10)[['nombre', 'capitalizacion_mercado_usd']]

df['ranking_cap_mercado'] = pd.to_numeric(df['ranking_cap_mercado'], errors='coerce')
# 4. Ordenar por 'ranking_cap_mercado'
df_ordenado_ranking_cap_mercado = df.sort_values(by='ranking_cap_mercado', ascending=True).head(10)[['nombre', 'ranking_cap_mercado']]

df['puntuacion_liquidez'] = pd.to_numeric(df['puntuacion_liquidez'], errors='coerce')
# 5. Ordenar por 'puntuacion_liquidez'
df_ordenado_puntuacion_liquidez = df.sort_values(by='puntuacion_liquidez', ascending=False).head(10)[['nombre', 'puntuacion_liquidez']]

df['puntuacion_comunidad'] = pd.to_numeric(df['puntuacion_comunidad'], errors='coerce')
# 6. Ordenar por 'puntuacion_comunidad' 
df_ordenado_puntuacion_comunidad = df.sort_values(by='puntuacion_comunidad', ascending=False).head(10)[['nombre', 'puntuacion_comunidad']]

df['porcentaje_votos_positivos'] = pd.to_numeric(df['porcentaje_votos_positivos'], errors='coerce')
# 7. Ordenar por 'porcentaje_votos_positivos' 
df_ordenado_porcentaje_votos_positivos = df.sort_values(by='porcentaje_votos_positivos', ascending=False).head(10)[['nombre', 'porcentaje_votos_positivos']]

df['usuarios_lista_seguimiento'] = pd.to_numeric(df['usuarios_lista_seguimiento'], errors='coerce')
# 8. Ordenar por 'usuarios_lista_seguimiento'
df_ordenado_usuarios_lista_seguimiento = df.sort_values(by='usuarios_lista_seguimiento', ascending=False).head(10)[['nombre', 'usuarios_lista_seguimiento']]

df['puntuacion_interes_publico'] = pd.to_numeric(df['puntuacion_interes_publico'], errors='coerce')
# 9. Ordenar por 'puntuacion_interes_publico'
df_ordenado_puntuacion_interes_publico = df.sort_values(by='puntuacion_interes_publico', ascending=False).head(10)[['nombre', 'puntuacion_interes_publico']]

df['volumen_total_usd'] = pd.to_numeric(df['volumen_total_usd'], errors='coerce')
# 10. Ordenar por 'volumen_total_usd'
df_ordenado_volumen_total_usd = df.sort_values(by='volumen_total_usd', ascending=False).head(10)[['nombre', 'volumen_total_usd']]

In [4]:
df_ordenado_ranking_coingecko

      nombre  ranking_coingecko
0    Bitcoin                  1
1   Ethereum                  2
4        XRP                  3
9     Solana                  4
3        BNB                  5
8   Dogecoin                  6
7    Cardano                  7
11  Polkadot                  9
10      TRON                 13
5   USD Coin                 28

In [5]:
df_ordenado_puntuacion_coingecko

      nombre  puntuacion_coingecko
0    Bitcoin                83.151
1   Ethereum                78.783
4        XRP                66.223
9     Solana                65.857
3        BNB                65.446
8   Dogecoin                65.012
7    Cardano                62.536
11  Polkadot                62.064
10      TRON                60.859
5   USD Coin                53.898

In [6]:
df_ordenado_capitalizacion_mercado_usd

              nombre  capitalizacion_mercado_usd
0            Bitcoin                503580110214
1           Ethereum                197248313062
2             Tether                 82774968781
3                BNB                 33367452194
4                XRP                 27501467937
5           USD Coin                 25875816011
6  Lido Staked Ether                 13736730865
7            Cardano                  9139380529
8           Dogecoin                  8771545732
9             Solana                  8269328828

In [7]:
df_ordenado_ranking_cap_mercado

              nombre  ranking_cap_mercado
0            Bitcoin                    1
1           Ethereum                    2
2             Tether                    3
3                BNB                    4
4                XRP                    5
5           USD Coin                    6
6  Lido Staked Ether                    7
7            Cardano                    8
8           Dogecoin                    9
9             Solana                   10

In [8]:
df_ordenado_puntuacion_liquidez

      nombre  puntuacion_liquidez
2     Tether              101.651
0    Bitcoin              100.011
1   Ethereum               95.183
5   USD Coin               87.410
4        XRP               81.070
9     Solana               74.593
3        BNB               73.073
7    Cardano               72.124
12   Polygon               68.532
10      TRON               67.924

In [9]:
df_ordenado_puntuacion_comunidad

               nombre  puntuacion_comunidad
0             Bitcoin                83.341
1            Ethereum                72.746
8            Dogecoin                71.666
3                 BNB                61.771
7             Cardano                58.753
4                 XRP                51.794
9              Solana                50.646
10               TRON                47.880
11           Polkadot                44.057
6   Lido Staked Ether                33.667

In [10]:
df_ordenado_porcentaje_votos_positivos

      nombre  porcentaje_votos_positivos
7    Cardano                       74.71
12   Polygon                       74.67
11  Polkadot                       71.74
4        XRP                       70.44
5   USD Coin                       69.23
1   Ethereum                       63.64
0    Bitcoin                       62.13
3        BNB                       61.82
9     Solana                       59.46
2     Tether                       56.25

In [11]:
df_ordenado_usuarios_lista_seguimiento

      nombre  usuarios_lista_seguimiento
0    Bitcoin                     1332601
1   Ethereum                     1194515
7    Cardano                      724997
3        BNB                      642994
4        XRP                      569536
9     Solana                      554152
12   Polygon                      545757
11  Polkadot                      514032
8   Dogecoin                      506468
2     Tether                      284379

In [12]:
df_ordenado_puntuacion_interes_publico

               nombre  puntuacion_interes_publico
3                 BNB                      11.364
1            Ethereum                       0.236
9              Solana                       0.104
0             Bitcoin                       0.073
12            Polygon                       0.053
5            USD Coin                       0.033
2              Tether                       0.029
6   Lido Staked Ether                       0.023
7             Cardano                       0.023
4                 XRP                       0.022

In [13]:
df_ordenado_volumen_total_usd

      nombre  volumen_total_usd
2     Tether        17454631744
1   Ethereum         7276891213
0    Bitcoin         5675162795
5   USD Coin         4054821069
4        XRP          865092243
3        BNB          392292742
9     Solana          277187182
12   Polygon          245724791
8   Dogecoin          231847821
7    Cardano          218389639

Eleccion de Criptomonedas Resultante:

**BTC (Bitcoin)**
- **Por qué es buena:** Bitcoin es la primera criptomoneda y es ampliamente reconocida como la principal moneda digital descentralizada. Su adopción masiva y la percepción de ser una reserva de valor le han otorgado el apodo de "oro digital".
- **Tecnología subyacente:** Utiliza una cadena de bloques (blockchain) de prueba de trabajo (PoW, Proof of Work) para procesar y verificar transacciones.
- **De qué se trata:** Bitcoin fue creado por una entidad anónima llamada Satoshi Nakamoto en 2008 y es una moneda digital descentralizada sin intermediarios.

**ETH (Ethereum)**
- **Por qué es buena:** Ethereum introdujo el concepto de contratos inteligentes al mundo de las criptomonedas, permitiendo la creación de aplicaciones descentralizadas (DApps, Aplicaciones Descentralizadas).
- **Tecnología subyacente:** También utiliza blockchain, pero a diferencia de Bitcoin, Ethereum está diseñado para soportar aplicaciones descentralizadas y contratos inteligentes.
- **De qué se trata:** Creado por Vitalik Buterin en 2015, Ethereum es una plataforma que permite a los desarrolladores crear y ejecutar contratos inteligentes y DApps.

**XRP (Ripple)**
- **Por qué es buena:** Ripple está enfocado en hacer que las transferencias transfronterizas sean rápidas y baratas.
- **Tecnología subyacente:** No utiliza blockchain en el sentido tradicional. En su lugar, utiliza un protocolo de consenso distribuido.
- **De qué se trata:** Ripple es tanto una plataforma como una moneda, y tiene el objetivo de permitir transferencias internacionales rápidas y de bajo costo.

**MATIC (Polygon)**
- **Por qué es buena:** Polygon busca solucionar los problemas de escalabilidad de Ethereum y mejorar su usabilidad al transformarlo en una blockchain multi-cadena.
- **Tecnología subyacente:** Es una capa de solución de segunda cadena que utiliza una combinación de redes PoS (Proof of Stake, Prueba de Participación) y PoA (Proof of Authority, Prueba de Autoridad).
- **De qué se trata:** Anteriormente conocido como Matic Network, Polygon proporciona herramientas escalables y compatibles con Ethereum para desarrolladores de DApps y empresas.

**SOL (Solana)**
- **Por qué es buena:** Solana ofrece soluciones de alto rendimiento y baja latencia para aplicaciones cripto.
- **Tecnología subyacente:** Solana utiliza una combinación de PoH (Proof of History, Prueba de Historia) y PoS (Proof of Stake, Prueba de Participación) para mejorar la velocidad y eficiencia de las transacciones.
- **De qué se trata:** Solana es una blockchain de alto rendimiento que busca proporcionar la infraestructura para DApps y criptomonedas descentralizadas.

**ADA (Cardano)**
- **Por qué es buena:** Cardano se describe a sí mismo como una blockchain de tercera generación y se centra en la sostenibilidad, interoperabilidad y escalabilidad.
- **Tecnología subyacente:** Utiliza un algoritmo PoS (Proof of Stake, Prueba de Participación) llamado Ouroboros.
- **De qué se trata:** Creado por uno de los co-fundadores de Ethereum, Charles Hoskinson, Cardano es una blockchain y plataforma de contrato inteligente basada en investigación académica.

**DOGE (Dogecoin)**
- **Por qué es buena:** Aunque comenzó como una broma, Dogecoin ha ganado popularidad por su comunidad activa y es utilizado frecuentemente para dar propinas y donaciones.
- **Tecnología subyacente:** Se basa en el código fuente de Litecoin y utiliza PoW (Proof of Work, Prueba de Trabajo).
- **De qué se trata:** Originalmente creado como una parodia de las criptomonedas basado en el meme "Doge", ha crecido en popularidad y ha sido adoptado en varias campañas benéficas y esfuerzos de crowdfunding.

**BNB (Binance Coin)**
- **Por qué es buena:** Originalmente creada como una token de utilidad para el intercambio Binance, se ha expandido en uso y valor.
- **Tecnología subyacente:** Inicialmente se lanzó en Ethereum, pero luego migró a su propia cadena de bloques, Binance Chain.
- **De qué se trata:** BNB fue creada por Binance, uno de los intercambios de criptomonedas más grandes del mundo, y se utiliza principalmente para pagar tarifas dentro de la plataforma

**DOT (Polkadot)**
- **Por qué es buena:** Polkadot se centra en la interoperabilidad, permitiendo que diferentes blockchains transfieran mensajes y valor de manera descentralizada y segura, facilitando la creación de aplicaciones que trabajan en múltiples cadenas a la vez.
- **Tecnología subyacente:** Polkadot utiliza un modelo multi-cadena con una cadena de retransmisión principal y múltiples cadenas paralelas. Esto permite que las transacciones se procesen en paralelo, aumentando la capacidad de procesamiento.
- **De qué se trata:** Creado por el Dr. Gavin Wood, uno de los co-fundadores de Ethereum, Polkadot tiene como objetivo conectar blockchains privados y públicos, consorcios y oráculos, permitiendo que estas diferentes cadenas compartan información y transacciones mediante su protocolo.

**USDT (Tether)**
- **Por qué es buena:** Tether es una de las primeras y más populares stablecoins (criptomonedas estabilizadas), lo que significa que su valor está atado a una moneda fiduciaria, en este caso, el dólar estadounidense. Esto proporciona estabilidad de precios en comparación con otras criptomonedas volátiles.
- **Tecnología subyacente:** Inicialmente se lanzó en la blockchain de Bitcoin a través del protocolo Omni, pero desde entonces ha sido emitida en otras blockchains, incluidas Ethereum, Tron y EOS.
- **De qué se trata:** Tether busca combinar la estabilidad de precio de las monedas fiduciarias con la libertad de las criptomonedas. Cada USDT emitido teóricamente está respaldado por un dólar estadounidense en reserva, aunque este punto ha sido objeto de debate y controversia.


### KPIs Seleccionados:

1. **Volatilidad del Precio (30 días)**
   - Razón: La volatilidad indica el nivel de riesgo asociado con la inversión en una criptomoneda. Una baja volatilidad puede indicar estabilidad, mientras que una alta volatilidad puede presentar oportunidades de inversión a corto plazo.

2. **Volumen de Comercio en 24h**
   - Razón: Un alto volumen de comercio sugiere una fuerte actividad y liquidez para la criptomoneda. Esto es crucial para los inversores que desean comprar o vender grandes cantidades sin afectar significativamente el precio.

3. **Capitalización de Mercado**
   - Razón: Representa el valor total de una criptomoneda y es un indicador de su popularidad y adopción en el mercado. Una alta capitalización puede ser una señal de confianza en esa criptomoneda.

Estos KPIs, junto con otros datos, se visualizan en el dashboard de Power BI, proporcionando una vista integral del mercado y ayudando a tomar decisiones informadas sobre inversiones en criptomonedas.

---

**Podran seguir los criterios de eleccion mas en profundidad en el archivo README.md del directorio**

---

In [2]:
import pandas as pd

# Leer el archivo CSV
df = pd.read_csv('KPIs_coingecko_kpis.csv')

# Columnas que contienen al menos un "Sin Dato"
cols_con_sin_dato = df.columns[df.isin(['Sin Dato']).any()].tolist()

# Contar cuántos "Sin Dato" hay en cada columna
conteo_sin_dato = df[cols_con_sin_dato].apply(lambda col: (col == 'Sin Dato').sum())

print("Columnas con 'Sin Dato':")
for col, count in conteo_sin_dato.items():
    print(f"- {col}: {count} valores 'Sin Dato'")

Columnas con 'Sin Dato':
- fecha_genesis: 8 valores 'Sin Dato'
- oferta_maxima: 7 valores 'Sin Dato'

---

**ETL: Únicas columnas que contienen valores faltantes son:<br>**
**fecha_genesis: fecha en que se creo la criptomoneda, columna no importante para nuestro análisis<br>**
**y oferta_maxima: tambien otra columna que no hemos de utilizar en nuestro análisis<br>**
**Por lo tanto dejamos esos datos tal cual como estan porque no nos influye a este análisis<br>**

---